# Generated by Django 4.0.3 on 2022-04-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20, null=True)),
                ('juridical_name', models.CharField(max_length=40, null=True)),
                ('payer_account_number', models.CharField(max_length=10, null=True)),
                ('bank_id', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
