# Generated by Django 4.0.3 on 2022-04-09 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('enterprise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_page.enterprise')),
            ],
            bases=('main_page.enterprise',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=30, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('passport_number', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('identification_number', models.CharField(max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('password', models.CharField(max_length=15, null=True)),
                ('online', models.BooleanField(default=False)),
                ('work_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.enterprise')),
            ],
        ),
    ]
