# Generated by Django 4.0.3 on 2022-04-11 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_transfer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
