# Generated by Django 4.0.3 on 2022-04-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
