# Generated by Django 4.0.3 on 2022-04-12 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_account_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='from_acc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.account'),
        ),
    ]
