# Generated by Django 4.0.3 on 2022-04-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_transfer_from_acc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='from_acc',
        ),
        migrations.AddField(
            model_name='transfer',
            name='accounts',
            field=models.ManyToManyField(null=True, to='main_page.account'),
        ),
    ]
