# Generated by Django 4.0.3 on 2022-04-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_remove_transfer_from_acc_transfer_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='accounts',
            field=models.ManyToManyField(to='main_page.account'),
        ),
    ]
