# Generated by Django 4.0.3 on 2022-04-14 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0014_transfer_chosen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_of_money', models.IntegerField(null=True)),
                ('count_of_month', models.IntegerField(null=True)),
                ('current', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.bank')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.user')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('installment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_page.installment')),
                ('percent', models.IntegerField(null=True)),
            ],
            bases=('main_page.installment',),
        ),
    ]
