# Generated by Django 4.0.3 on 2022-04-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0015_installment_credit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credit',
        ),
    ]
