# Generated by Django 4.0.3 on 2022-04-12 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_manager_not_approved_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='on_work',
        ),
    ]
