# Generated by Django 4.0.3 on 2022-04-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_transfer_from_acc'),
        ('office', '0005_remove_manager_on_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='operations',
            field=models.ManyToManyField(to='main_page.transfer'),
        ),
    ]
